import 'curriculum_model.dart';

final List<MakautSubject> staticSubjects = [
  MakautSubject(
    code: 'ES-CS201',
    name: 'Programming for Problem Solving',
    semester: 2,
    icon: 'terminal',
    color: 'primary',
  ),
  MakautSubject(
    code: 'BS-M101',
    name: 'Mathematics - IA',
    semester: 1,
    icon: 'calculate',
    color: 'primary',
  ),
  MakautSubject(
    code: 'BS-M201',
    name: 'Mathematics - IIA',
    semester: 2,
    icon: 'functions',
    color: 'primary',
  ),
  MakautSubject(
    code: 'BS-PH101',
    name: 'Physics - I',
    semester: 1,
    icon: 'science',
    color: 'primary',
  ),
  MakautSubject(
    code: 'BS-CH201',
    name: 'Chemistry - I',
    semester: 2,
    icon: 'science',
    color: 'tertiary',
  ),
  MakautSubject(
    code: 'ES-EE101',
    name: 'Basic Electrical Engineering',
    semester: 1,
    icon: 'bolt',
    color: 'primary',
  ),
  MakautSubject(
    code: 'HM-HU201',
    name: 'English',
    semester: 2,
    icon: 'book',
    color: 'outline',
  ),
  MakautSubject(
    code: 'ES-ME191',
    name: 'Engineering Graphics & Design',
    semester: 1,
    icon: 'draw',
    color: 'outline',
  ),
];

final List<CurriculumTopic> staticTopics = [
  CurriculumTopic(
    id: 'cs-u1-1',
    subject: 'Programming for Problem Solving',
    subjectCode: 'ES-CS201',
    semester: 2,
    module: 'Unit 1: Introduction to Programming',
    topic: 'Computer System Components & Memory Locations',
    subtopic: 'Disks, memory, processor, OS, compilers, source code, variables and data types',
    difficulty: 'easy',
    moodSuitability: ['low', 'sad', 'okay', 'good'],
    learningType: 'learning',
    priority: 'medium',
    subjectColor: 'primary',
    estimatedDuration: '20 mins',
  ),
  CurriculumTopic(
    id: 'cs-u1-2',
    subject: 'Programming for Problem Solving',
    subjectCode: 'ES-CS201',
    semester: 2,
    module: 'Unit 1: Introduction to Programming',
    topic: 'Algorithm Representation & Flowcharts',
    subtopic: 'Steps to solve logical & numerical problems, Flowchart and Pseudocode',
    difficulty: 'easy',
    moodSuitability: ['low', 'sad', 'okay', 'good'],
    learningType: 'learning',
    priority: 'medium',
    subjectColor: 'primary',
    estimatedDuration: '20 mins',
  ),
  CurriculumTopic(
    id: 'cs-u2-1',
    subject: 'Programming for Problem Solving',
    subjectCode: 'ES-CS201',
    semester: 2,
    module: 'Unit 2: Arithmetic Expressions',
    topic: 'Arithmetic Expressions and Precedence',
    subtopic: 'Evaluation of operators, precedence and associativity',
    difficulty: 'easy',
    moodSuitability: ['low', 'sad', 'okay'],
    learningType: 'practice',
    priority: 'medium',
    subjectColor: 'primary',
    estimatedDuration: '15 mins',
  ),
  CurriculumTopic(
    id: 'cs-u3-1',
    subject: 'Programming for Problem Solving',
    subjectCode: 'ES-CS201',
    semester: 2,
    module: 'Unit 3: Conditional Branching & Loops',
    topic: 'Conditionals & If-Else Branching',
    subtopic: 'Evaluation of conditionals, nested if-else structures',
    difficulty: 'easy',
    moodSuitability: ['low', 'sad', 'okay', 'good'],
    learningType: 'practice',
    priority: 'high',
    subjectColor: 'primary',
    estimatedDuration: '20 mins',
  ),
  CurriculumTopic(
    id: 'cs-u3-2',
    subject: 'Programming for Problem Solving',
    subjectCode: 'ES-CS201',
    semester: 2,
    module: 'Unit 3: Conditional Branching & Loops',
    topic: 'Iteration & Loops (For, While, Do-While)',
    subtopic: 'Loop execution, termination conditions, iterative series calculation',
    difficulty: 'medium',
    moodSuitability: ['okay', 'good', 'great'],
    learningType: 'practice',
    priority: 'high',
    subjectColor: 'primary',
    estimatedDuration: '25 mins',
  ),
  CurriculumTopic(
    id: 'cs-u4-1',
    subject: 'Programming for Problem Solving',
    subjectCode: 'ES-CS201',
    semester: 2,
    module: 'Unit 4: Arrays & Strings',
    topic: '1D & 2D Arrays and String Manipulation',
    subtopic: 'Array traversal, character arrays, string operations',
    difficulty: 'medium',
    moodSuitability: ['good', 'okay', 'great'],
    learningType: 'learning',
    priority: 'high',
    subjectColor: 'primary',
    estimatedDuration: '30 mins',
  ),
  CurriculumTopic(
    id: 'cs-u5-1',
    subject: 'Programming for Problem Solving',
    subjectCode: 'ES-CS201',
    semester: 2,
    module: 'Unit 5: Basic Algorithms',
    topic: 'Searching & Basic Sorting Algorithms',
    subtopic: 'Linear Search, Binary Search, Bubble Sort, Insertion Sort, Selection Sort',
    difficulty: 'medium',
    moodSuitability: ['good', 'great'],
    learningType: 'practice',
    priority: 'high',
    subjectColor: 'primary',
    estimatedDuration: '35 mins',
  ),
  CurriculumTopic(
    id: 'cs-u6-1',
    subject: 'Programming for Problem Solving',
    subjectCode: 'ES-CS201',
    semester: 2,
    module: 'Unit 6: Functions & Call by Value/Reference',
    topic: 'Functions & Parameter Passing',
    subtopic: 'Function prototypes, call by value, passing arrays as call by reference',
    difficulty: 'medium',
    moodSuitability: ['good', 'great', 'okay'],
    learningType: 'learning',
    priority: 'medium',
    subjectColor: 'primary',
    estimatedDuration: '30 mins',
  ),
  CurriculumTopic(
    id: 'cs-u7-1',
    subject: 'Programming for Problem Solving',
    subjectCode: 'ES-CS201',
    semester: 2,
    module: 'Unit 7: Recursion & Advanced Sorting',
    topic: 'Recursive Calls, Factorial, Fibonacci & Quick/Merge Sort',
    subtopic: 'Base conditions, call stack, Ackerman function, Quick Sort, Merge Sort',
    difficulty: 'hard',
    moodSuitability: ['great', 'stressed'],
    learningType: 'practice',
    priority: 'high',
    subjectColor: 'primary',
    estimatedDuration: '45 mins',
  ),
  CurriculumTopic(
    id: 'cs-u8-1',
    subject: 'Programming for Problem Solving',
    subjectCode: 'ES-CS201',
    semester: 2,
    module: 'Unit 8: Structures',
    topic: 'Structures & Array of Structures',
    subtopic: 'Defining structures, accessing members, array of structures',
    difficulty: 'hard',
    moodSuitability: ['great', 'good'],
    learningType: 'learning',
    priority: 'medium',
    subjectColor: 'primary',
    estimatedDuration: '35 mins',
  ),
  CurriculumTopic(
    id: 'cs-u9-1',
    subject: 'Programming for Problem Solving',
    subjectCode: 'ES-CS201',
    semester: 2,
    module: 'Unit 9: Pointers',
    topic: 'Pointer Fundamentals & Self-Referential Structures',
    subtopic: 'Pointer declaration, dereferencing, concept of linked lists',
    difficulty: 'hard',
    moodSuitability: ['great', 'stressed'],
    learningType: 'practice',
    priority: 'high',
    subjectColor: 'primary',
    estimatedDuration: '40 mins',
  ),
  CurriculumTopic(
    id: 'cs-u10-1',
    subject: 'Programming for Problem Solving',
    subjectCode: 'ES-CS201',
    semester: 2,
    module: 'Unit 10: File Handling',
    topic: 'File Input/Output Operations',
    subtopic: 'fopen, fclose, fread, fwrite, macros and header inclusions',
    difficulty: 'hard',
    moodSuitability: ['great', 'good'],
    learningType: 'learning',
    priority: 'medium',
    subjectColor: 'primary',
    estimatedDuration: '35 mins',
  ),
  CurriculumTopic(
    id: 'cs-u11-1',
    subject: 'Programming for Problem Solving',
    subjectCode: 'ES-CS201',
    semester: 2,
    module: 'Unit 11: Dynamic Memory Allocation',
    topic: 'Malloc, Calloc, Realloc & Memory Leak Prevention',
    subtopic: 'Dynamic memory management, heap allocation, free function',
    difficulty: 'hard',
    moodSuitability: ['great', 'stressed'],
    learningType: 'practice',
    priority: 'high',
    subjectColor: 'primary',
    estimatedDuration: '30 mins',
  ),
  CurriculumTopic(
    id: 'm1-u1-1',
    subject: 'Mathematics - IA',
    subjectCode: 'BS-M101',
    semester: 1,
    module: 'Module 1: Calculus (Integration)',
    topic: 'Improper Integrals, Beta & Gamma Functions',
    subtopic: 'Evolutes, involutes, surface areas and volumes of revolutions',
    difficulty: 'hard',
    moodSuitability: ['great', 'good'],
    learningType: 'practice',
    priority: 'high',
    subjectColor: 'primary',
    estimatedDuration: '40 mins',
  ),
  CurriculumTopic(
    id: 'm1-u2-1',
    subject: 'Mathematics - IA',
    subjectCode: 'BS-M101',
    semester: 1,
    module: 'Module 2: Calculus (Differentiation)',
    topic: 'Rolle’s & Mean Value Theorems, Taylor & Maclaurin Series',
    subtopic: 'Indeterminate forms, L Hospital rule, Maxima and minima',
    difficulty: 'medium',
    moodSuitability: ['good', 'great', 'okay'],
    learningType: 'learning',
    priority: 'medium',
    subjectColor: 'primary',
    estimatedDuration: '30 mins',
  ),
  CurriculumTopic(
    id: 'm1-u3-1',
    subject: 'Mathematics - IA',
    subjectCode: 'BS-M101',
    semester: 1,
    module: 'Module 3: Matrices',
    topic: 'Matrix Rank, Linear Independence & Gauss Elimination',
    subtopic: 'Determinants, Cramer rule, inverse of matrix, Gauss-Jordan',
    difficulty: 'hard',
    moodSuitability: ['great', 'stressed'],
    learningType: 'practice',
    priority: 'high',
    subjectColor: 'primary',
    estimatedDuration: '45 mins',
  ),
  CurriculumTopic(
    id: 'm1-u4-1',
    subject: 'Mathematics - IA',
    subjectCode: 'BS-M101',
    semester: 1,
    module: 'Module 4 & 5: Vector Spaces & Eigenvalues',
    topic: 'Vector Spaces, Linear Transformations & Eigenvalues/Eigenvectors',
    subtopic: 'Basis, Dimension, Rank-Nullity theorem, Diagonalization, Gram-Schmidt',
    difficulty: 'hard',
    moodSuitability: ['great', 'stressed'],
    learningType: 'practice',
    priority: 'high',
    subjectColor: 'primary',
    estimatedDuration: '50 mins',
  ),
  CurriculumTopic(
    id: 'm1-u5-1',
    subject: 'Mathematics - IA',
    subjectCode: 'BS-M101',
    semester: 1,
    module: 'Module 6: Multivariable Calculus',
    topic: 'Partial Derivatives & Euler’s Theorem on Homogeneous Functions',
    subtopic: 'Total derivatives, Jacobians, Multivariable Maxima & Minima',
    difficulty: 'hard',
    moodSuitability: ['great', 'good'],
    learningType: 'practice',
    priority: 'high',
    subjectColor: 'primary',
    estimatedDuration: '40 mins',
  ),
  CurriculumTopic(
    id: 'm2-u1-1',
    subject: 'Mathematics - IIA',
    subjectCode: 'BS-M201',
    semester: 2,
    module: 'Module 1: Basic Probability',
    topic: 'Probability Spaces, Random Variables & Bernoulli Trials',
    subtopic: 'Conditional probability, Poisson & Binomial distributions, Expectation, Variance',
    difficulty: 'medium',
    moodSuitability: ['good', 'okay', 'great'],
    learningType: 'learning',
    priority: 'high',
    subjectColor: 'primary',
    estimatedDuration: '35 mins',
  ),
  CurriculumTopic(
    id: 'm2-u2-1',
    subject: 'Mathematics - IIA',
    subjectCode: 'BS-M201',
    semester: 2,
    module: 'Module 2 & 3: Continuous & Bivariate Distributions',
    topic: 'Normal, Exponential & Gamma Distributions & Bayes Rule',
    subtopic: 'Continuous random variables, distribution functions, conditional densities',
    difficulty: 'hard',
    moodSuitability: ['great', 'good'],
    learningType: 'practice',
    priority: 'high',
    subjectColor: 'primary',
    estimatedDuration: '40 mins',
  ),
  CurriculumTopic(
    id: 'm2-u4-1',
    subject: 'Mathematics - IIA',
    subjectCode: 'BS-M201',
    semester: 2,
    module: 'Module 4 & 5: Basic & Applied Statistics',
    topic: 'Measures of Central Tendency, Correlation & Regression',
    subtopic: 'Moments, Skewness, Kurtosis, Curve fitting by least squares',
    difficulty: 'easy',
    moodSuitability: ['okay', 'low', 'good', 'sad'],
    learningType: 'revision',
    priority: 'medium',
    subjectColor: 'primary',
    estimatedDuration: '25 mins',
  ),
  CurriculumTopic(
    id: 'm2-u5-1',
    subject: 'Mathematics - IIA',
    subjectCode: 'BS-M201',
    semester: 2,
    module: 'Module 6: Sampling & Hypothesis Testing',
    topic: 'Large & Small Sample Tests (t-Test, Chi-Square & F-Test)',
    subtopic: 'Hypothesis testing, confidence intervals, significance level',
    difficulty: 'hard',
    moodSuitability: ['great', 'stressed'],
    learningType: 'practice',
    priority: 'high',
    subjectColor: 'primary',
    estimatedDuration: '35 mins',
  ),
  CurriculumTopic(
    id: 'ch-u1-1',
    subject: 'Chemistry - I',
    subjectCode: 'BS-CH201',
    semester: 2,
    module: 'Module 1: Atomic & Molecular Structure',
    topic: 'Molecular Orbitals & Crystal Field Theory',
    subtopic: 'Schrodinger equation, H2 energy level diagrams, Pi-orbitals of benzene, Band structure',
    difficulty: 'medium',
    moodSuitability: ['good', 'okay'],
    learningType: 'learning',
    priority: 'medium',
    subjectColor: 'tertiary',
    estimatedDuration: '30 mins',
  ),
  CurriculumTopic(
    id: 'ch-u2-1',
    subject: 'Chemistry - I',
    subjectCode: 'BS-CH201',
    semester: 2,
    module: 'Module 2: Spectroscopic Techniques',
    topic: 'Vibrational, Rotational & NMR Spectroscopy',
    subtopic: 'Selection rules, electronic spectroscopy, fluorescence, MRI applications',
    difficulty: 'medium',
    moodSuitability: ['good', 'great'],
    learningType: 'learning',
    priority: 'medium',
    subjectColor: 'tertiary',
    estimatedDuration: '30 mins',
  ),
  CurriculumTopic(
    id: 'ch-u3-1',
    subject: 'Chemistry - I',
    subjectCode: 'BS-CH201',
    semester: 2,
    module: 'Module 3: Intermolecular Forces',
    topic: 'Ionic, Dipolar & Van Der Waals Interactions',
    subtopic: 'Equations of state of real gases, critical phenomena',
    difficulty: 'easy',
    moodSuitability: ['low', 'sad', 'okay'],
    learningType: 'revision',
    priority: 'low',
    subjectColor: 'tertiary',
    estimatedDuration: '20 mins',
  ),
  CurriculumTopic(
    id: 'ch-u4-1',
    subject: 'Chemistry - I',
    subjectCode: 'BS-CH201',
    semester: 2,
    module: 'Module 4: Chemical Equilibria & Free Energy',
    topic: 'Thermodynamics, Free Energy & Nernst Equation',
    subtopic: 'Entropy, cell potentials, acid-base solubility equilibria, corrosion, Ellingham diagrams',
    difficulty: 'medium',
    moodSuitability: ['good', 'okay', 'great'],
    learningType: 'practice',
    priority: 'high',
    subjectColor: 'tertiary',
    estimatedDuration: '30 mins',
  ),
  CurriculumTopic(
    id: 'ch-u5-1',
    subject: 'Chemistry - I',
    subjectCode: 'BS-CH201',
    semester: 2,
    module: 'Module 5: Periodic Properties',
    topic: 'Effective Nuclear Charge, Electronegativity & HSAB',
    subtopic: 'Ionization energy, electron affinity, polarizability, HSAB, geometries',
    difficulty: 'easy',
    moodSuitability: ['low', 'sad', 'okay'],
    learningType: 'revision',
    priority: 'medium',
    subjectColor: 'tertiary',
    estimatedDuration: '20 mins',
  ),
  CurriculumTopic(
    id: 'ch-u6-1',
    subject: 'Chemistry - I',
    subjectCode: 'BS-CH201',
    semester: 2,
    module: 'Module 6: Stereochemistry',
    topic: 'Chirality, Enantiomers, Diastereomers & Conformational Analysis',
    subtopic: 'Optical activity, 3D representations, isomerism in transition metals',
    difficulty: 'easy',
    moodSuitability: ['okay', 'low', 'good', 'sad'],
    learningType: 'learning',
    priority: 'medium',
    subjectColor: 'tertiary',
    estimatedDuration: '25 mins',
  ),
  CurriculumTopic(
    id: 'ph-u1-1',
    subject: 'Physics - I',
    subjectCode: 'BS-PH101',
    semester: 1,
    module: 'Module 1: Mechanics',
    topic: 'Harmonic Oscillators, Resonance & Rigid Body Dynamics',
    subtopic: 'Constraints, friction, potential energy gradient, damped motion, moment of inertia',
    difficulty: 'hard',
    moodSuitability: ['great', 'good'],
    learningType: 'practice',
    priority: 'high',
    subjectColor: 'primary',
    estimatedDuration: '40 mins',
  ),
  CurriculumTopic(
    id: 'ph-u2-1',
    subject: 'Physics - I',
    subjectCode: 'BS-PH101',
    semester: 1,
    module: 'Module 2: Optics',
    topic: 'Fraunhofer & Fresnel Diffraction, Polarisation & Lasers',
    subtopic: 'Single/double slit, grating resolution, optical activity, population inversion',
    difficulty: 'medium',
    moodSuitability: ['good', 'okay', 'great'],
    learningType: 'learning',
    priority: 'medium',
    subjectColor: 'primary',
    estimatedDuration: '30 mins',
  ),
  CurriculumTopic(
    id: 'ph-u3-1',
    subject: 'Physics - I',
    subjectCode: 'BS-PH101',
    semester: 1,
    module: 'Module 3: Electromagnetic Theory',
    topic: 'Maxwell’s Equations, Poynting Vector & Electromagnetic Waves',
    subtopic: 'Gauss law, Ampere law, Faraday law, wave propagation in dielectric media',
    difficulty: 'hard',
    moodSuitability: ['great', 'stressed'],
    learningType: 'practice',
    priority: 'high',
    subjectColor: 'primary',
    estimatedDuration: '35 mins',
  ),
  CurriculumTopic(
    id: 'ph-u4-1',
    subject: 'Physics - I',
    subjectCode: 'BS-PH101',
    semester: 1,
    module: 'Module 4: Quantum Mechanics',
    topic: 'Schrodinger Equation, Particle in a Box & Uncertainty Principle',
    subtopic: 'Black body radiation, de Broglie hypothesis, quantum harmonic oscillator, H-atom',
    difficulty: 'hard',
    moodSuitability: ['great', 'stressed'],
    learningType: 'practice',
    priority: 'high',
    subjectColor: 'primary',
    estimatedDuration: '45 mins',
  ),
  CurriculumTopic(
    id: 'ee-u1-1',
    subject: 'Basic Electrical Engineering',
    subjectCode: 'ES-EE101',
    semester: 1,
    module: 'Module 1: DC Circuits',
    topic: 'Kirchhoff’s Laws, Superposition & Thevenin/Norton Theorems',
    subtopic: 'Electrical elements R, L, C, time-domain RL and RC circuits',
    difficulty: 'medium',
    moodSuitability: ['good', 'okay', 'great'],
    learningType: 'practice',
    priority: 'high',
    subjectColor: 'primary',
    estimatedDuration: '30 mins',
  ),
  CurriculumTopic(
    id: 'ee-u2-1',
    subject: 'Basic Electrical Engineering',
    subjectCode: 'ES-EE101',
    semester: 1,
    module: 'Module 2: AC Circuits',
    topic: 'Phasor Representation, RLC Resonance & Star-Delta Connections',
    subtopic: 'Sinusoidal waveforms, real/reactive power, power factor, 3-phase balanced circuits',
    difficulty: 'hard',
    moodSuitability: ['great', 'good'],
    learningType: 'practice',
    priority: 'high',
    subjectColor: 'primary',
    estimatedDuration: '40 mins',
  ),
  CurriculumTopic(
    id: 'ee-u3-1',
    subject: 'Basic Electrical Engineering',
    subjectCode: 'ES-EE101',
    semester: 1,
    module: 'Module 3: Transformers',
    topic: 'Single Phase Transformers, Equivalent Circuit & Efficiency',
    subtopic: 'EMF equation, losses, regulation, open circuit & short circuit tests',
    difficulty: 'medium',
    moodSuitability: ['good', 'okay'],
    learningType: 'learning',
    priority: 'medium',
    subjectColor: 'primary',
    estimatedDuration: '35 mins',
  ),
  CurriculumTopic(
    id: 'ee-u4-1',
    subject: 'Basic Electrical Engineering',
    subjectCode: 'ES-EE101',
    semester: 1,
    module: 'Module 4: Electrical Machines',
    topic: '3-Phase Induction Motors & DC Motors',
    subtopic: 'Rotating magnetic fields, torque-slip characteristic, speed control, synchronous generators',
    difficulty: 'hard',
    moodSuitability: ['great', 'good'],
    learningType: 'learning',
    priority: 'medium',
    subjectColor: 'primary',
    estimatedDuration: '35 mins',
  ),
  CurriculumTopic(
    id: 'hu-u1-1',
    subject: 'English',
    subjectCode: 'HM-HU201',
    semester: 2,
    module: 'Unit 1: Vocabulary Building',
    topic: 'Word Formation, Roots, Prefixes & Suffixes',
    subtopic: 'Compounding, clipping, blending, Greek/Latin roots, synonyms, antonyms, acronyms',
    difficulty: 'easy',
    moodSuitability: ['low', 'sad', 'okay'],
    learningType: 'learning',
    priority: 'low',
    subjectColor: 'outline',
    estimatedDuration: '15 mins',
  ),
  CurriculumTopic(
    id: 'hu-u2-1',
    subject: 'English',
    subjectCode: 'HM-HU201',
    semester: 2,
    module: 'Unit 2: Basic Writing Skills',
    topic: 'Sentence Structures, Punctuation & Coherence',
    subtopic: 'Simple, compound, complex sentences, active/passive voice, paragraph organization',
    difficulty: 'easy',
    moodSuitability: ['low', 'sad', 'okay'],
    learningType: 'practice',
    priority: 'low',
    subjectColor: 'outline',
    estimatedDuration: '15 mins',
  ),
  CurriculumTopic(
    id: 'hu-u3-1',
    subject: 'English',
    subjectCode: 'HM-HU201',
    semester: 2,
    module: 'Unit 3: Identifying Common Errors in Writing',
    topic: 'Subject-Verb & Noun-Pronoun Agreement',
    subtopic: 'Misplaced modifiers, articles, prepositions, redundancies, clichés',
    difficulty: 'easy',
    moodSuitability: ['okay', 'low', 'sad'],
    learningType: 'revision',
    priority: 'medium',
    subjectColor: 'outline',
    estimatedDuration: '15 mins',
  ),
  CurriculumTopic(
    id: 'hu-u5-1',
    subject: 'English',
    subjectCode: 'HM-HU201',
    semester: 2,
    module: 'Unit 5: Writing Practices',
    topic: 'Comprehension, Précis Writing & Technical Email/CV',
    subtopic: 'Essay writing, business letters, cover letter & CV preparation',
    difficulty: 'easy',
    moodSuitability: ['okay', 'sad', 'good'],
    learningType: 'practice',
    priority: 'medium',
    subjectColor: 'outline',
    estimatedDuration: '20 mins',
  ),
  CurriculumTopic(
    id: 'me-u2-1',
    subject: 'Engineering Graphics & Design',
    subjectCode: 'ES-ME191',
    semester: 1,
    module: 'Module 2: Lettering, Dimensioning, Scales',
    topic: 'Plain Scale, Diagonal Scale & Vernier Scales',
    subtopic: 'Principles of engineering drawing, line types, dimensioning standards',
    difficulty: 'easy',
    moodSuitability: ['low', 'sad', 'okay'],
    learningType: 'learning',
    priority: 'low',
    subjectColor: 'outline',
    estimatedDuration: '20 mins',
  ),
  CurriculumTopic(
    id: 'me-u7-1',
    subject: 'Engineering Graphics & Design',
    subjectCode: 'ES-ME191',
    semester: 1,
    module: 'Module 7 & 9: Isometric Projections & CAD',
    topic: 'Isometric Scale & CAD Drawing Fundamentals',
    subtopic: 'Conversion of isometric to orthographic views, CAD toolbars and coordinate entries',
    difficulty: 'medium',
    moodSuitability: ['good', 'okay'],
    learningType: 'practice',
    priority: 'medium',
    subjectColor: 'outline',
    estimatedDuration: '25 mins',
  ),
];
